org: brh55
app: okta-identity-x
service: okta-identity-x

frameworkVersion: '2'
plugins:
  - serverless-plugin-include-dependencies
  - serverless-dotenv-plugin
package:
  excludeDevDependencies: false

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  inline:
    handler: inline.handler
    events:
      - http:
          path: /inline
          method: post
          cors: true
  createSession:
    handler: createSession.handler
    events:
      - http:
          path: /createSession
          method: post
          cors: true
  register:
    handler: register.handler
    events:
      - http:
          path: /register
          method: post
          cors: true